### ISSUE TITLE
remove FDP_DAR_EXT.1.1

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/operatingsystem#11]
We need language in the intro that talks about how we expect the AO or system owner to seek evaluation for DAR capabilities.  It is not in the threat model for this PP.

We will  want to cover activation of DAR in FMT_SMF/MOF -- perhaps add that, based on MDF PP (or simpler ones like the Browser PP)?

**Comment by ajcousi** [comment]
FDP_DAR_EXT.1.1 removed. Wording still needs updating in SMF/MOF

**Comment by kgal** [comment]
I added a section in the intro under the TOE Boundary, called TOE Platform, and tried to explain that DAR is outside the scope.

**Comment by kgal** [comment]
I also added DAR configuration under FMT_SMF/MOF.
