### ISSUE TITLE
HTML / XML sources of the 4.3 version?

### ISSUE THREAD

**Issue by adelton** [commoncriteria/operatingsystem#116]
Hello,

I can see that pp_os_v4.3 was released on 2022-09-27 at https://www.niap-ccevs.org/Profile/Info.cfm?PPID=469&id=469.

Sadly, there is only PDF document available there, no HTML format of the Protection Profile like 4.2.1 had at https://www.niap-ccevs.org/Profile/Info.cfm?PPID=442&id=442.

What is the relationship of the 4.3 version to this repository? The https://commoncriteria.github.io/pp/operatingsystem/operatingsystem-release.html which shows the 2022-09-27 date suggests it might ... but there is no branch or tag for 4.3 here.

Could the authoritative HTML version of the Protection Profile get added to https://www.niap-ccevs.org/Profile/Info.cfm?PPID=469&id=469 and the release tagged in this repo?

Thank you, Jan

**Comment by kgal** [comment]
Jan,

This was the source for the published PDF. I have branched the 4.3 release (as "release-4.3") and I will follow up with NIAP to get the HTML version published.

kg

**Comment by adelton** [comment]
Awesome, thank you.

**Comment by adelton** [comment]
There is now https://www.niap-ccevs.org/MMO/PP/OS%204.3%20PP (redirecting to https://www.niap-ccevs.org/MMO/PP/OS%204.3%20PP/) linked from https://www.niap-ccevs.org/Profile/Info.cfm?PPID=469&id=469, and its content matches the current  https://commoncriteria.github.io/pp/operatingsystem/operatingsystem-release.html.

Thank you for prompt resolution.
