### ISSUE TITLE
FDP_DDM_EXT.1 need more information

### ISSUE THREAD

**Issue by amkgi** [commoncriteria/operatingsystem#119]
I am trying to find more info about FDP_DDM_EXT.1, but cannot any publications with them, only another components of FDP class can find be. Could you prompt me where I can find info about FDP_DDM_EXT.1?

**Comment by zsmi** [comment]
@amkgi Are you sure FDP_DDM_EXT.1 is correct? That's not in the Operating System Protection Profile and FDP_DDM isn't even part of the Common Criteria catalog. Where did you see this requirement listed?

**Comment by amkgi** [comment]
@zsmi Yes, I wrote it correctly. But you really won't find FDP_DDM in the CC. I have seen this requirement in this [PP](https://fstec.ru/files/583/---8--2017-/1098/--------.pdf) and probably this extension is a special case of this PP. But I was hoping that this is not the case and tried to find sources describing FDP_DDM.

**Comment by zsmi** [comment]
Closing ticket as this appears to be a phishing attempt.
