### ISSUE TITLE
FMT_SMF_RMT.1.1 - selection needs to be updated.

### ISSUE THREAD

**Issue by zsmi** [commoncriteria/operatingsystem#15]
The the selection for [FMT_SMF_RMT.1.1](http://common-criteria.rhcloud.com/operatingsystem/output/operatingsystem-release.html#FMT_SMF_RMT.1.1), FTP_ITC.1 does not exist in the OS PP. We need to add FTP_ITC.1.1 or remove this selection.

allow management functions also to be performed from a remote IT entity using a trusted channel established in accordance with the requirements stated in FTP_ITC.1.

**Comment by kgal** [comment]
Added FTP_ITC.1.
