### ISSUE TITLE
FCS_TLSC_EXT.1.3 - Application note needs updating or requirement needs to be added

### ISSUE THREAD

**Issue by zsmi** [commoncriteria/operatingsystem#16]
The application note on [FCS_TLSC_EXT.1.3](http://common-criteria.rhcloud.com/operatingsystem/output/operatingsystem-release.html#FCS_TLSC_EXT.1.3) needs to be updated to not talk about FCS_HTTPS_EXT.1 or the FCS_HTTPS_EXT.1 requirement needs to be added to the PP.

**Comment by kgal** [comment]
Removed. The OS PP seems to be HTTPS agnostic right now.
