### ISSUE TITLE
FCS_COP.1.1(1) Application note needs to be updated.

### ISSUE THREAD

**Issue by zsmi** [commoncriteria/operatingsystem#17]
FCS_CKM.1(1) does not exist in this PP so it either needs to be added or the link needs to be removed from the application note of [FCS_COP.1.1(1)](http://common-criteria.rhcloud.com/operatingsystem/output/operatingsystem-release.html#FCS_COP.1.1(1))

**Comment by kgal** [comment]
This issue exists in the ApSo PP as well :(.

**Comment by kgal** [comment]
We have FCS_CKM.1 so I pointed the reference at that.
