### ISSUE TITLE
Per Platform AA?  See FPT_AEX_EXT.1.2

### ISSUE THREAD

**Issue by bourdett** [commoncriteria/operatingsystem#18]
Req for testing DEP. The AA here currently says "The method of doing so varies per platform."

Are we doing platform specific AA for this PP, like AppPP, or are we keeping the tests generic enough for any OS

**Comment by kgal** [comment]
Definitely an artifact from the ApSo. They need  to be generic. Unless platform refers to ARM, x86, x86-64,...
