### ISSUE TITLE
Style of FMT_SMF ?

### ISSUE THREAD

**Issue by bourdett** [commoncriteria/operatingsystem#19]
I see three style for FMT_SMF / MOF across our PPs. Which one do we want to use? 

Numbered List: (mdm pp)
http://common-criteria.rhcloud.com/mdm/output/mdm-release.html#FMT_SMF.1.1(1)

List of Selections: (app pp)
http://common-criteria.rhcloud.com/application/output/application.html#FMT_SMF.1.1

Numbered table with alternating line colors (this is for an fmt_mof, but we could adopt the style for fmt_smf)
http://common-criteria.rhcloud.com/emailclient/output/emailclient-release.html#FMT_MOF_EXT.1.1

**Comment by jeffblank** [comment]
i suggest alternating line colors, with no numbering.  so basically like
the email client.

the numbers just force people to look at another document and make
maintenance harder

**Comment by kgal** [comment]
Attempt 1 at fixing this:
	      <management-function-set>
		<manager>Administrator</manager>
		<manager>User</manager>
		<management-function roles="User,Administrator">aaaa</management-function>
		<management-function roles="User"> bbbb </management-function> 
creates a email PP- like table.
