### ISSUE TITLE
rework FCS_TLSC_EXT into separate components

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/operatingsystem#23]
... or at least try to do so.  This is because only components, not elements, should be individually objective/optional.

**Comment by jeffblank** [comment]
I'll sort this out later.  Leave as-is for this round.  There are implications for several existing and future PPs.

**Comment by kgal** [comment]
fcs_tlsc_ext.1.4, fcs_tlsc_ext.1.5, fcs_tlsc_ext.1.6", fpt_aslr_ext.1.2, fia_x509_ext.2.2, are all elements whose status does not match it's parent.

**Comment by kgal** [comment]
Addressed by d17c126
