### ISSUE TITLE
FAU_GEN.1.1 - more tests or defer for annex?

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/operatingsystem#33]
We need to decide whether to add more audit events as noted in https://github.com/commoncriteria/operatingsystem/wiki/Analysis-of-DISA-OS-Security-Requirements-Guide
or to let them get added to a DoD Annex, where they could grow without bound.

**Comment by ajcousi** [comment]
Can we not limit the audit to only specific security issues (failed log on etc) - anything else isn't a security thing surely.

**Comment by ajcousi** [comment]
updated FAU_GEN.1.1 to include more tests from http://www.sandia.gov/FSO/PDF/flowdown/Final_CNSSI_1253.pdf
