### ISSUE TITLE
FTA_TAB banner thing (optional)

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/operatingsystem#34]
this does not have any relationship to computer security or legal precedent, but we need FTA_TAB as an optional requirement.  DISA will need to claim it is required, at least for configuration, so that they can express this in the DoD Annex.

**Comment by ajcousi** [comment]
This is surely a policy issue and not a security enforcing function - are we not keeping the PP to only security enforcing functionality???

**Comment by jeffblank** [comment]
indeed it is not about security, and does not address any threat.  configuring it is a policy requirement for some customers.  however, we want the opportunity for CC test labs to be able to test it, so that those customers are able to achieve maximum value from the CC testing process.
