### ISSUE TITLE
FPT_ITC -- allow IPSec

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/operatingsystem#38]
with reference to IPSec client PP.

**Comment by ajcousi** [comment]
updated in https://github.com/commoncriteria/operatingsystem/commit/7e560e833324e89e5f2a148128c0c489a294359b however not sure if that's how you'd like it stated (not sure how to link out to the IPsec PP either)

**Comment by jeffblank** [comment]
Looks good to me, and nicely it's identical to what we did in the MDF PP.  Still want to resolve the one complaint about it...
