### ISSUE TITLE
FTP_TRP.1.1 needs an assurance activity

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/operatingsystem#40]
take it from the ND cPP

**Comment by ajcousi** [comment]
There's no assurance activities listed in the CPP for this? I can take them from the PP instead?

**Comment by ajcousi** [comment]
updated to cover the tests.

**Comment by kgal** [comment]
Are the assurance activities listed under FTP_TRP.1.3 meant for 1.1 and 1.2 too?

**Comment by ajcousi** [comment]
I think so - but wasn't sure how to do it?

**Comment by kgal** [comment]
Added a note that explicitly stated this.
