### ISSUE TITLE
FAU_GEN.1.1 - clarify language

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/operatingsystem#47]
Clarification for:

Administrator or root-level access events (Success/Failure);

turn this into something about recording privileged commands -- will also satisfy DISA want

**Comment by ajcousi** [comment]
Updated to make it a selectable item - as per commit https://github.com/commoncriteria/operatingsystem/commit/5301b3eb2be60736cc1637d57b37c1acde58733d
