### ISSUE TITLE
FCS_RBG_EXT.1.1

### ISSUE THREAD

**Issue by bourdett** [commoncriteria/operatingsystem#5]
It seems like FCS_RBG_EXT.2.1 is covering RBG generation. What is RBG_EXT1.1 saying? Is this, we want the OS to provide an API for calling for RBG?

"The OS shall implement functionality for its cryptographic operations."

that just sounds really vague. I dont even know what that is saying.

and the AA is to verify that FCS_RBG_EXT.2 is in the ST? Since FCS_RBG_EXT.2 is not optional/objective/selection then it had better be in the ST, do we need a test for that?

**Comment by ajcousi** [comment]
removed - agreed it didn't add anything.

**Comment by ajcousi** [comment]
Agreed - I don't see what it's actually adding - anyone else got thoughts on this or shall we just remove?

**Comment by jeffblank** [comment]
yes plz

**Comment by ajcousi** [comment]
removed
