### ISSUE TITLE
do we add SSH as a trusted path?

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/operatingsystem#50]
requested.

**Comment by kgal** [comment]
Why are we adding SSH Clients requirements? SSH Server requirements make sense to me, in that for a OS to be remotely administered with SSH you should have SSH Server requirements. SSH Client is just an application... Not logically part of this protection profile. (Although it doesn't really fit in the ApSo PP).

**Comment by jeffblank** [comment]
An OS could act as a client in order to connect out to a management server to get settings, for example.  

But indeed I'd like to remove this too, or at least combine it with the server.  It's OK as is, but we should talk to Mary since this text is what was in the ND cPP.  The bigger problem is verbose language in a cPP, as it is something on which we should be converging.  Let's chat tomorrow!

**Comment by kgal** [comment]
Okay. That makes sense.
