### ISSUE TITLE
Optional mandatory requirements [sic]

### ISSUE THREAD

**Issue by kgal** [commoncriteria/operatingsystem#52]
fcs_tlsc_ext.1.1 has the following note:

	      If <i>implement TLS 1.2 (RFC 5246)</i> is selected, then 
	      <linkref linkend="FCS_CKM.2.1"/>,    <linkref linkend="FCS_COP.1.1(1)"/>, 
	      <linkref linkend="FCS_COP.1.1(2)"/>, <linkref linkend="FCS_COP.1.1(3)"/>, and 
	      <linkref linkend="FCS_COP.1.1(4)"/> are required. 

which kinda implies that those requirements are selection-based, but they're not. What is this trying to say?

**Comment by ajcousi** [comment]
Rewrite to mandate that TLS 1.2 is supported? 

Rewrite suggestion:

FCS_CKM.2.1, FCS_COP.1.1(1)...etc... are mandatory requirments to ensure TLS 1.2 operates in a conformant manner?

Or...

Ensure that all the tests listed aren't marked as optional?

**Comment by jeffblank** [comment]
This is a vestige of copy-paste from the App PP.  After copy-pasting that document, it should have been scrubbed.

**Comment by kgal** [comment]
Scrubbed
