### ISSUE TITLE
prohibit read access of certain files in FDP_ACF_EXT.1

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/operatingsystem#54]
or in FPT_ACF_EXT.1.  This is to ensure that things which require confidentiality (e.g. audit logs) have it.

**Comment by kgal** [comment]
FDP_ACF_EXT.1 has been modified to prevent 'accessing' and not specifically 'modifiying'. Since audit logs are not going to be owned by a regular user, this should be okay. Thoughts?

**Comment by jeffblank** [comment]
That helps, but we still need it in FPT (Protection of TSF).  I added a new requirement -- hopefully this will do it.
