### ISSUE TITLE
Optional requiremnt for Mandatory Access Control

### ISSUE THREAD

**Issue by kgal** [commoncriteria/operatingsystem#55]
Should we include one?

FDP_IFC_EXT.1.1: The OS shall have a mechanism to prohibit a information channel between two unprivileged processes without the assistance of the kernel or other processes.

Basically I'm trying to say that pick two processes, any processes. Can they be configured such that one process cannot read any object that the 2nd process can write to? The CDS team thought this would be helpful. Also MRAT is requesting a similar thing from MDF PP.

**Comment by jeffblank** [comment]
MLS or other fancy access controls should be in an EP.
