### ISSUE TITLE
FPT_TST_EXT.1.1 - rework assurance activity

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/operatingsystem#59]
make sure we are not levying hardware requirements.  finesse the hardware-protected definition.

**Comment by ajcousi** [comment]
The issue with this is that we really do require the hashes to be held somewhere in hardware - unless we're going from the first part of the kernel loading, if that's the case then we can remove all the hardware bits.

**Comment by kgal** [comment]
Closing after a week of no complaints.
