### ISSUE TITLE
discuss vpn pp req in os pp for trusted path

### ISSUE THREAD

**Issue by bourdett** [commoncriteria/operatingsystem#78]
FCS_IPSEC_EXT.1.1 through FCS_IPSEC_EXT.1.12
from
https://www.niap-ccevs.org/pp/pp_vpn_ipsec_client_v1.4.pdf

**Comment by jeffblank** [comment]
Discussed.  Tentatively we plan to keep the current form, which would require an additional evaluation for VPN functionality.

This should motivate reworking of the VPN PP as an EP, which is the desired end state.
