### ISSUE TITLE
FAU_GEN.1.2 - Question about AA

### ISSUE THREAD

**Issue by bourdett** [commoncriteria/operatingsystem#79]
http://common-criteria.rhcloud.com/operatingsystem/output/operatingsystem-release.html#FAU_GEN.1.2

AA - The evaluator will ensure that ALL logged events written to the system logging service contain the following information.

Do we really want labs checking ALL events? There are literally 10,000's of unique events in most OS's. Checking them all will be costly? Could we modify it to something like check only the events called out in FAU_GEN.1.1 (or something to limit the number of events the lab is expected to check)

thoughts?

**Comment by jeffblank** [comment]
Done.
