### ISSUE TITLE
FPT_LIB_EXT.1.1 - rewrite as SAR

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/operatingsystem#8]
This is useful information, but something that could be captured in an SAR instead for an OS.

**Comment by ajcousi** [comment]
How about we move this information to 5.2.4 Class ALC: Life-cycle Support as it's about supporting the platform going forward.

**Comment by ajcousi** [comment]
Moved to alc_tsu_ext.1.4c (and dremoved FPT_LIB_EXT.1.1) as per commit https://github.com/commoncriteria/operatingsystem/commit/a4d917949cb3608b99292eb0e2b344211f839ad3
