### ISSUE TITLE
Why did we do 2 req for basically the same thing? FIA_X509_EXT.2.1 &  FIA_X509_EXT.2.2

### ISSUE THREAD

**Issue by bourdett** [commoncriteria/operatingsystem#81]
http://common-criteria.rhcloud.com/operatingsystem/output/operatingsystem-release.html#FIA_X509_EXT.2.1

http://common-criteria.rhcloud.com/operatingsystem/output/operatingsystem-release.html#FIA_X509_EXT.2.2

In the App PP we have 1 req for this and we made it a selection?
The application shall use X.509v3 certificates as defined by RFC 5280 to support authentication for [selection: HTTPS , TLS , DTLS ] .

In OS could we do just 1 requirement that is sel-based on FTP_ITC_EXT.1.1
The OS shall use X.509v3 certificates as defined by RFC 5280 to support authentication for [selection: TLS , DTLS ] connections.

The MDF PP also only has 1 req for this: It is

FIA_X509_EXT.2.1 The TSF shall use X.509v3 certificates as defined by RFC 5280 to
support authentication for EAP-TLS exchanges, and [selection: IPsec, TLS, HTTPS, DTLS]],
and [selection: code signing for system software updates, code signing for mobile
applications, code signing for integrity verification, [assignment: other uses], no additional
uses].

**Comment by jeffblank** [comment]
Elements merged.
