### ISSUE TITLE
Include requirements for PIN-like unlock capabilities

### ISSUE THREAD

**Issue by kgal** [commoncriteria/operatingsystem#83]
Systems that store keys in mechanisms of high trust, should be able to unlock the keys and the larger system with a simple pin. Requirements (and selections) like key wrapping , need to be added to facilitate this.

**Comment by jeffblank** [comment]
Given the nascent effort for a Discrete Storage Component, maybe this should be handled there, i.e. in the future?  Also please avoid terms like "high trust" -- people will start getting all EAL-ish about it, and we all know that's nonsense.  Let's talk tomorrow...

**Comment by ajcousi** [comment]
I wouldn't call an OS that didn't provide PIN unlock neglegent though - this sounds like a nice to have but not a mandatory security enforcing function.

**Comment by kgal** [comment]
This requirement is for systems like Microsoft Passport (hence the bourdett assignment).

**Comment by kgal** [comment]
Added joe's stuff.
