### ISSUE TITLE
update Position Statement for OS PP?

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/operatingsystem#92]
Sync with NIAP.  We seem to like OS evaluations now.

**Comment by jeffblank** [comment]
Or do nothing.  Nobody can seem to find it on the NIAP web site anyway.  So maybe it will just go by the wayside.

**Comment by bourdett** [comment]
I emailed NIAP about this on 4/5/2016. It really should be removed, or replaced
https://www.niap-ccevs.org/Documents_and_Guidance/ccevs/GPOS%20Position%20Statement.pdf

**Comment by bourdett** [comment]
Cant find this on NIAP site anymore. This was probably resolved a long time ago. Closing
